# Generated by Django 3.2.6 on 2021-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
