# Generated by Django 3.2.6 on 2022-01-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_imageoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
